ce100_hw3_algo_lib_cs.Huffman.HuffmanTree Class Reference
Public Member Functions
void Build (string source)
BitArray Encode (string source)
string Decode (BitArray bits)
bool IsLeaf (Node node)
Public Attributes
Dictionary< char, int > Frequencies = new Dictionary<char, int>()
Properties
Node Root [get, set]
Detailed Description
Definition at line 127 of file Huffman.cs.
Member Function Documentation
Build()
void ce100_hw3_algo_lib_cs.Huffman.HuffmanTree.Build (string source)
Definition at line 137 of file Huffman.cs.
            {
                // For each character of the source text
                for (int i = 0; i < source.Length; i++)
                {
                    // If it is not in the dictionary, appends it and sets its frequency to 0.
                    if (!Frequencies.ContainsKey(source[i]))
                    {
                        Frequencies.Add(source[i], 0);
                    }
                    // Increase the frequency by one.
                    Frequencies[source[i]]++;
                }
                // For each symbol in the dictionary
                foreach (KeyValuePair<char, int> symbol in Frequencies)
                {
                    // Creates a node and adds it to the list.
                    nodes.Add(new Node()
                    {
                        Symbol = symbol.Key,
                        Frequency = symbol.Value
                    });
                }
                // Until the list is single element
                while (nodes.Count > 1)
                {
                    // Sorts the list by frequency.
                    List<Node> orderedNodes = nodes.OrderBy(node => node.Frequency).ToList<Node>();
                    // If there are at least two elements
                    if (orderedNodes.Count >= 2)
                    {
                        // Gets the first two elements.
                        List<Node> taken = orderedNodes.Take(2).ToList<Node>();
                        // Creates the common parent of these two elements.
                        Node parent = new Node()
                        {
                            Symbol = '*',
                            Frequency = taken[0].Frequency + taken[1].Frequency,
                            Left = taken[0],
                            Right = taken[1]
                        };
                        // Removes the received elements from the list.
                        nodes.Remove(taken[0]);
                        nodes.Remove(taken[1]);
                        // Ebeveyni listeye ekler.
                        nodes.Add(parent);
                    }
                    // Updates the root node.
                    this.Root = nodes.FirstOrDefault();
                }
            }
References ce100_hw3_algo_lib_cs.Huffman.HuffmanTree.Frequencies, and ce100_hw3_algo_lib_cs.Huffman.Node.Frequency.
Decode()
string ce100_hw3_algo_lib_cs.Huffman.HuffmanTree.Decode (BitArray bits)
Definition at line 214 of file Huffman.cs.
            {
                // Variable to hold the current node
                Node current = this.Root;
                // Decoded text
                string decoded = "";
                // For each bit of the bit array
                foreach (bool bit in bits)
                {
                    // If bit is 1, it goes to the lower right branch.
                    if (bit)
                    {
                        if (current.Right != null)
                        {
                            current = current.Right;
                        }
                    }
                    // If bit is 0, it goes to the lower left branch.
                    else
                    {
                        if (current.Left != null)
                        {
                            current = current.Left;
                        }
                    }
                    // If the leaf has arrived at the node
                    if (IsLeaf(current))
                    {
                        // Adds the node's symbol to the text.
                        decoded += current.Symbol;
                        // Resets the current node to the root.
                        current = this.Root;
                    }
                }
                // Returns the decoded text.
                return decoded;
            }
References ce100_hw3_algo_lib_cs.Huffman.HuffmanTree.IsLeaf(), ce100_hw3_algo_lib_cs.Huffman.Node.Left, ce100_hw3_algo_lib_cs.Huffman.Node.Right, ce100_hw3_algo_lib_cs.Huffman.HuffmanTree.Root, and ce100_hw3_algo_lib_cs.Huffman.Node.Symbol.
Encode()
BitArray ce100_hw3_algo_lib_cs.Huffman.HuffmanTree.Encode (string source)
Definition at line 194 of file Huffman.cs.
            {
                // List to hold encoded text
                List<bool> encodedSource = new List<bool>();
                // For each character of the source text
                for (int i = 0; i < source.Length; i++)
                {
                    // Finds the encoded version of the character in the tree.
                    List<bool> encodedSymbol = this.Root.Traverse(source[i], new List<bool>());
                    // Adds the encoded character to the list.
                    encodedSource.AddRange(encodedSymbol);
                }
                // Converts list elements to a bit array.
                BitArray bits = new BitArray(encodedSource.ToArray());
                // Returns the bit array.
                return bits;
            }
References ce100_hw3_algo_lib_cs.Huffman.HuffmanTree.Root, and ce100_hw3_algo_lib_cs.Huffman.Node.Traverse().
IsLeaf()
bool ce100_hw3_algo_lib_cs.Huffman.HuffmanTree.IsLeaf (Node node)
Definition at line 255 of file Huffman.cs.
            {
                // Checks if the node is a leaf.
                // If it has no left and right child branches, it is a leaf
                return (node.Left == null && node.Right == null);
            }
References ce100_hw3_algo_lib_cs.Huffman.Node.Left, and ce100_hw3_algo_lib_cs.Huffman.Node.Right.
Referenced by ce100_hw3_algo_lib_cs.Huffman.HuffmanTree.Decode().
Member Data Documentation
Frequencies
Dictionary<char, int> ce100_hw3_algo_lib_cs.Huffman.HuffmanTree.Frequencies = new Dictionary<char, int>()
Definition at line 135 of file Huffman.cs.
Referenced by ce100_hw3_algo_lib_cs.Huffman.HuffmanTree.Build().
Property Documentation
Root
Node ce100_hw3_algo_lib_cs.Huffman.HuffmanTree.Root [get], [set]
Definition at line 130 of file Huffman.cs.
            {
                get;
                set;
            }
Referenced by ce100_hw3_algo_lib_cs.Huffman.HuffmanTree.Decode(), and ce100_hw3_algo_lib_cs.Huffman.HuffmanTree.Encode().
The documentation for this class was generated from the following file:
ce100-hw3-algo-lib-cs/Huffman.cs