ce100_hw3_algo_lib_cs.Huffman.Node_mp3 Class Reference
Public Member Functions
List< bool > Traverse_mp3 (byte? symbol, List< bool > data)
Properties
byte Symbol [get, set]
int Frequency [get, set]
Node_mp3 Left [get, set]
Node_mp3 Right [get, set]
Detailed Description
Definition at line 271 of file Huffman.cs.
Member Function Documentation
Traverse_mp3()
List< bool > ce100_hw3_algo_lib_cs.Huffman.Node_mp3.Traverse_mp3 (byte? symbol, List< bool > data)
Definition at line 294 of file Huffman.cs.
            {
                if (Left == null && Right == null)
                {
                    // Returns the data if the symbol is equal to this node's symbol.
                    if (Symbol == symbol)
                    {
                        return data;
                    }
                    // If not, returns null.
                    else
                    {
                        return null;
                    }
                }
                else
                {
                    // Variables to hold left and right sub-branches
                    List<bool> left = null;
                    List<bool> right = null;
                    // If there is a left lower branch
                    if (Left != null)
                    {
                        // Creates the left path.
                        List<bool> leftPath = new List<bool>();
                        leftPath.AddRange(data);
                        leftPath.Add(false);
                        // Searches for the symbol in the lower left branch.
                        left = Left.Traverse_mp3(symbol, leftPath);
                    }
                    // If there is a lower right branch
                    if (Right != null)
                    {
                        // Creates the right path.
                        List<bool> rightPath = new List<bool>();
                        rightPath.AddRange(data);
                        rightPath.Add(true);
                        // Searches for the symbol in the lower right branch.
                        right = Right.Traverse_mp3(symbol, rightPath);
                    }
                    // Returns the left path if it found the left sub-branch.
                    if (left != null)
                    {
                        return left;
                    }
                    // Returns the right path if found in the right sub-branch.
                    else
                    {
                        return right;
                    }
                }
            }
References ce100_hw3_algo_lib_cs.Huffman.Node_mp3.Left, ce100_hw3_algo_lib_cs.Huffman.Node_mp3.Right, ce100_hw3_algo_lib_cs.Huffman.Node_mp3.Symbol, and ce100_hw3_algo_lib_cs.Huffman.Node_mp3.Traverse_mp3().
Referenced by ce100_hw3_algo_lib_cs.Huffman.HuffmanTree_mp3.Encode(), and ce100_hw3_algo_lib_cs.Huffman.Node_mp3.Traverse_mp3().
Property Documentation
Frequency
int ce100_hw3_algo_lib_cs.Huffman.Node_mp3.Frequency [get], [set]
Definition at line 278 of file Huffman.cs.
            {
                get;
                set;
            }
Referenced by ce100_hw3_algo_lib_cs.Huffman.HuffmanTree_mp3.Build().
Left
Node_mp3 ce100_hw3_algo_lib_cs.Huffman.Node_mp3.Left [get], [set]
Definition at line 283 of file Huffman.cs.
            {
                get;
                set;
            }
Referenced by ce100_hw3_algo_lib_cs.Huffman.HuffmanTree_mp3.IsLeaf(), and ce100_hw3_algo_lib_cs.Huffman.Node_mp3.Traverse_mp3().
Right
Node_mp3 ce100_hw3_algo_lib_cs.Huffman.Node_mp3.Right [get], [set]
Definition at line 288 of file Huffman.cs.
            {
                get;
                set;
            }
Referenced by ce100_hw3_algo_lib_cs.Huffman.HuffmanTree_mp3.IsLeaf(), and ce100_hw3_algo_lib_cs.Huffman.Node_mp3.Traverse_mp3().
Symbol
byte ce100_hw3_algo_lib_cs.Huffman.Node_mp3.Symbol [get], [set]
Definition at line 273 of file Huffman.cs.
            {
                get;
                set;
            }
Referenced by ce100_hw3_algo_lib_cs.Huffman.Node_mp3.Traverse_mp3().
The documentation for this class was generated from the following file:
C:/Users/Administrator/Desktop/ce100-hw3-sln/ce100-hw3-algo-lib-cs/Huffman.cs