ce100_hw3_algo_lib_cs.Huffman.HuffmanTree_mp3 Class Reference
Public Member Functions
void Build (byte[] source)
BitArray Encode (byte[] source)
byte[] Decode (BitArray bits)
bool IsLeaf (Node_mp3 node)
Public Attributes
Dictionary< byte, int > Frequencies = new Dictionary<byte, int>()
Properties
Node_mp3 Root [get, set]
Detailed Description
Definition at line 351 of file Huffman.cs.
Member Function Documentation
Build()
void ce100_hw3_algo_lib_cs.Huffman.HuffmanTree_mp3.Build (byte[] source)
Definition at line 361 of file Huffman.cs.
            {
                // For each byte of the source array
                for (int i = 0; i < source.Length; i++)
                {
                    // If it is not in the dictionary, add it and set its frequency to 0.
                    if (!Frequencies.ContainsKey(source[i]))
                    {
                        Frequencies.Add(source[i], 0);
                    }
                    // Increases the frequency by one.
                    Frequencies[source[i]]++;
                }
                // For each symbol in the dictionary
                foreach (KeyValuePair<byte, int> symbol in Frequencies)
                {
                    // Create a node and add it to the list.
                    nodes.Add(new Node_mp3()
                    {
                        Symbol = symbol.Key,
                        Frequency = symbol.Value
                    });
                }
                // Until the list is single element
                while (nodes.Count > 1)
                {
                    // Sorts the list by frequency.
                    List<Node_mp3> orderedNodes = nodes.OrderBy(node => node.Frequency).ToList<Node_mp3>();
                    // If there are at least two elements
                    if (orderedNodes.Count >= 2)
                    {
                        // Gets the first two elements.
                        List<Node_mp3> taken = orderedNodes.Take(2).ToList<Node_mp3>();
                        // Creates the common parent of these two elements.
                        Node_mp3 parent = new Node_mp3()
                        {
                            Symbol = byte.MaxValue, // The parent has no symbol.
                            Frequency = taken[0].Frequency + taken[1].Frequency,
                            Left = taken[0],
                            Right = taken[1]
                        };
                        // Removes the received elements from the list.
                        nodes.Remove(taken[0]);
                        nodes.Remove(taken[1]);
                        // Adds the parent to the list.
                        nodes.Add(parent);
                    }
                    // Updates the root node.
                    this.Root = nodes.FirstOrDefault();
                }
            }
References ce100_hw3_algo_lib_cs.Huffman.HuffmanTree_mp3.Frequencies, and ce100_hw3_algo_lib_cs.Huffman.Node_mp3.Frequency.
Decode()
byte[] ce100_hw3_algo_lib_cs.Huffman.HuffmanTree_mp3.Decode (BitArray bits)
Definition at line 437 of file Huffman.cs.
            {
                // Variable to hold the current node
                Node_mp3 current = this.Root;
                // List to hold the decoded array
                List<byte> decoded = new List<byte>();
                // For each bit of the bit array
                foreach (bool bit in bits)
                {
                    // If bit is 1, it goes to the lower right branch.
                    if (bit)
                    {
                        if (current.Right != null)
                        {
                            current = current.Right;
                        }
                    }
                    // If bit is 0, it goes to the lower left branch.
                    else
                    {
                        if (current.Left != null)
                        {
                            current = current.Left;
                        }
                    }
                    // If the leaf has arrived at the node
                    if (IsLeaf(current))
                    {
                        // Adds the node's symbol to the list.
                        decoded.Add(current.Symbol);
                        // Resets the current node to the root.
                        current = this.Root;
                    }
                }
                // Returns the decoded array.
                return decoded.ToArray();
            }
References ce100_hw3_algo_lib_cs.Huffman.HuffmanTree_mp3.IsLeaf(), and ce100_hw3_algo_lib_cs.Huffman.HuffmanTree_mp3.Root.
Encode()
BitArray ce100_hw3_algo_lib_cs.Huffman.HuffmanTree_mp3.Encode (byte[] source)
Definition at line 417 of file Huffman.cs.
            {
                // List to hold the encoded array
                List<bool> encodedSource = new List<bool>();
                // For each byte of the source array
                for (int i = 0; i < source.Length; i++)
                {
                    // Finds the encoded byte in the tree.
                    List<bool> encodedSymbol = this.Root.Traverse_mp3(source[i], new List<bool>());
                    // Add the encoded byte to the list
                    encodedSource.AddRange(encodedSymbol);
                }
                // Converts list elements to a bit array.
                BitArray bits = new BitArray(encodedSource.ToArray());
                // Returns the bit array.
                return bits;
            }
References ce100_hw3_algo_lib_cs.Huffman.HuffmanTree_mp3.Root, and ce100_hw3_algo_lib_cs.Huffman.Node_mp3.Traverse_mp3().
IsLeaf()
bool ce100_hw3_algo_lib_cs.Huffman.HuffmanTree_mp3.IsLeaf (Node_mp3 node)
Definition at line 478 of file Huffman.cs.
            {
                // Checks if the node is a leaf.
                // If it has no left or right child branches, it is a leaf.
                return (node.Left == null && node.Right == null);
            }
References ce100_hw3_algo_lib_cs.Huffman.Node_mp3.Left, and ce100_hw3_algo_lib_cs.Huffman.Node_mp3.Right.
Referenced by ce100_hw3_algo_lib_cs.Huffman.HuffmanTree_mp3.Decode().
Member Data Documentation
Frequencies
Dictionary<byte, int> ce100_hw3_algo_lib_cs.Huffman.HuffmanTree_mp3.Frequencies = new Dictionary<byte, int>()
Definition at line 359 of file Huffman.cs.
Referenced by ce100_hw3_algo_lib_cs.Huffman.HuffmanTree_mp3.Build().
Property Documentation
Root
Node_mp3 ce100_hw3_algo_lib_cs.Huffman.HuffmanTree_mp3.Root [get], [set]
Definition at line 354 of file Huffman.cs.
            {
                get;
                set;
            }
Referenced by ce100_hw3_algo_lib_cs.Huffman.HuffmanTree_mp3.Decode(), and ce100_hw3_algo_lib_cs.Huffman.HuffmanTree_mp3.Encode().
The documentation for this class was generated from the following file:
C:/Users/Administrator/Desktop/ce100-hw3-sln/ce100-hw3-algo-lib-cs/Huffman.cs